apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resource-configs
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploys AFTER operators app syncs
spec:
  project: default
  source:
    repoURL: git@github.com:mallmen/openshift-config.git
    targetRevision: HEAD
    path: cluster-configs/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true # Prevents CRD check failure
