apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-api-cert
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  commonName: api.ocp4.mikea.net
  dnsNames:
  - "api.ocp4.mikea.net"
  issuerRef:
    name: custom-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: custom-api-cert-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

