---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: idm-bind-password
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgB5PLGeGIPS8UcVg735+/Jb+KhbVq5YshKM6HallNOqEkOlM4P4LdeQJNmTXhPUB1GBvx7ZAR/cLysPxOL7b9jhTVJ2pzwUVj8nBNViYKcG1216EjCrikV7DkPK4VVUYE0Ua7NfRGy63bNv3HzM/oLjq1N7GSRXoaTfehnhAlAyP5oDWwhvjzkGmaETMKNcsWVjYpnZXqIDTk+frxNeJ9N56y8XbMSqAxKV7Hj55ix1tjLMPc6j+iOysPduSdn51gXNJD/AR+EDl5EFPNlf1vSGSFG/5H8iN5iIB4u9voWPCTVlSEtBSnWllk5GnmfeeSWHuPy2gP5jYPoTD0ZSKeaKpY07IlsgaeMXAHzYRAEmTPL0HtMRP1H0K4ySQ2xTMluBRy1le+lb5BWbqu8KSuuJ2IV41340Av12iPP++0Y07vww36AOuvKLfueHR3l4zks+3YPmCIBZJvHFCAGg7rVqTmNUyJPXw3CZ75uMxU8GoBDmphga/mhyoBK0VheQI1E0d6kmPV8lQrhWyO8QuwDBwLOGeTmsU204KpBDT9tWKosMWiZ8GgSsiT7PI9Qb95hCe0MbR5MmD7JUE9rN7TO+jRjEV0wyozauiBHXR64Kar1P7amupT4GoJnQ9VeBkO2GZB3xGMY/wnW5zZ1WmqJud43s2m67GLbf5SqUMev0QcTfmmWTlmwKPd/TbyIMAGxXN+005xVPyw==
  template:
    metadata:
      name: idm-bind-password
      namespace: openshift-config
