apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-ingress-cert
  namespace: openshift-ingress
spec:
  commonName: "*.apps.ocp4.mikea.net"
  dnsNames:
  - "*.apps.ocp4.mikea.net"
  - "apps.ocp4.mikea.net"
  issuerRef:
    name: custom-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: custom-ingress-cert-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

